repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.224
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^collections/.*
      - id: trailing-whitespace
        exclude: ^collections/.*
